// Code generated by build_time_stamp.pl. DO NOT EDIT.
package common

import "time"

// BuildStamp is the time and date when the program was last built.
var BuildStamp = time.Date(2025, 9, 8, 14, 49, 49, 0, time.Local)

